### ISSUE TITLE
User not logged

### ISSUE THREAD

**Issue by jekayode** [jimfrenette/laravel-ajax-validation#1]
After the user clicked the link in the email. It goes straight to the login page with any information to the User and when the user enter his password, he gets "You need to confirm your account. We have sent you an activation code, please check your e-mail."

Please what could I have been doing wrong? I followed the tutorial to the letter.

Thanks

**Comment by jimfrenette** [comment]
Hello,
The activation link in the email goes to the /user/activation/{token} route,
Then it calls the activateUser method in app/Http/Controllers/Auth/AuthController.php
Make sure the token in the email link exist for the user in the user_activations table 

Check the code against yours in this branch:
https://github.com/jimfrenette/laravel-ajax-validation/tree/email-activation

**Comment by jimfrenette** [comment]
Re-tested the code in the email-activation branch. When a token exists for the user, the user will be activated and logged in via  /user/activation/{token}
